name: CI Pipeline for Model Training

on:
  push:
    branches:
      - main

# Memberi izin bot untuk 'menulis' (push) balik ke repo
permissions:
  contents: write

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Siapkan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install dependencies manual (agar lebih cepat daripada Conda)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn

      # 4. Jalankan MLflow Project
      # Kita arahkan ke folder 'MLProject'
      # Kita pakai --env-manager=local supaya dia pakai library yang barusan kita install di atas
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      # 5. Simpan Artefak (Commit folder mlruns ke GitHub)
      # Ini memenuhi syarat 'Skilled': Menyimpan artefak ke repositori
      - name: Commit and Push Artifacts
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Tambahkan folder mlruns (hasil training)
          git add MLProject/mlruns
          
          # Commit dan Push
          git commit -m "Auto: Add training artifacts (mlruns)" || echo "No changes to commit"
          git push